import { Template } from '../types';

export const shopifyProductsTemplate: Template = {
  key: 'shopify-products',
  title: 'Shopify Products',
  templateVersion: '2025.1.0',
  ruleVersion: '1.0.0',
  sourceUrls: [
    'https://help.shopify.com/en/manual/products/import-export/using-csv',
    'https://help.shopify.com/en/manual/products/import-export/import-products',
    'https://help.shopify.com/en/manual/products/import-export/common-import-issues'
  ],
  lastVerified: '2025-01-14',
  notes: [
    'Based on official Shopify CSV import specifications (2025)',
    'UTF-8 encoding required, comma-separated values',
    'TRUE/FALSE required for Published field (coerces yes/no/1/0)',
    'Status must be active, draft, or archived (case-insensitive)',
    'Variant Price must be numeric and ≥ 0 (no currency symbols)',
    'Handle should be URL-friendly (lowercase, hyphens)',
    'Inventory Policy must be deny or continue',
    'Required: Title (for new products), Handle (for variants)',
  ],
  fields: [
    {
      key: 'title',
      label: 'Title',
      required: true,
      type: 'string',
      transform: ['trim'],
      synonyms: ['name', 'product title', 'product name', 'título', 'titulo', 'nom', 'bezeichnung', 'nome'],
    },
    {
      key: 'handle',
      label: 'Handle',
      required: true,
      type: 'string',
      transform: ['trim'],
      synonyms: ['slug', 'url handle', 'product handle', 'identificador', 'poignée', 'griff'],
    },
    {
      key: 'status',
      label: 'Status',
      required: true,
      type: 'enum',
      enumValues: ['active', 'draft', 'archived'],
      transform: ['trim', 'lower'],
      synonyms: ['state', 'product status'],
    },
    {
      key: 'published',
      label: 'Published',
      required: true,
      type: 'boolean',
      transform: ['boolean'],
      synonyms: ['visible', 'is live', 'is published'],
    },
    {
      key: 'variant_sku',
      label: 'Variant SKU',
      required: true,
      type: 'string',
      transform: ['trim', 'upper'],
      synonyms: ['sku', 'product sku', 'código', 'code', 'artikelnummer', 'codice'],
    },
    {
      key: 'variant_price',
      label: 'Variant Price',
      required: true,
      type: 'number',
      transform: ['number'],
      synonyms: ['price', 'cost', 'amount', 'precio', 'prix', 'preis', 'prezzo', 'coût', 'costo'],
    },
    {
      key: 'body_html',
      label: 'Body (HTML)',
      type: 'string',
      synonyms: ['description', 'body', 'content'],
    },
    {
      key: 'vendor',
      label: 'Vendor',
      type: 'string',
      transform: ['trim'],
      synonyms: ['brand', 'manufacturer', 'supplier'],
    },
    {
      key: 'product_category',
      label: 'Product Category',
      type: 'string',
      transform: ['trim'],
      synonyms: ['category', 'type', 'product type'],
    },
    {
      key: 'tags',
      label: 'Tags',
      type: 'string',
      transform: ['trim'],
      synonyms: ['keywords', 'labels'],
    },
    {
      key: 'variant_inventory_qty',
      label: 'Variant Inventory Qty',
      type: 'number',
      transform: ['number'],
      synonyms: ['inventory', 'qty', 'stock', 'quantity', 'available', 'inventario', 'cantidad', 'quantité', 'bestand', 'menge', 'quantità', 'disponible'],
    },
    {
      key: 'variant_inventory_policy',
      label: 'Variant Inventory Policy',
      type: 'enum',
      enumValues: ['deny', 'continue'],
      transform: ['trim', 'lower'],
      synonyms: ['backorders', 'inventory policy', 'out of stock policy'],
    },
    {
      key: 'image_src',
      label: 'Image Src',
      type: 'string',
      transform: ['trim'],
      synonyms: ['image url', 'photo', 'image', 'picture'],
    },
  ],
};