import { Template } from '../types';

export const shopifyProductsTemplate: Template = {
  key: 'shopify-products',
  title: 'Shopify Products',
  notes: [
    'TRUE/FALSE required for Published field',
    'Status must be active, draft, or archived',
    'Variant Price must be numeric and ≥ 0',
    'Handle should be URL-friendly (lowercase, hyphens)',
  ],
  fields: [
    {
      key: 'title',
      label: 'Title',
      required: true,
      type: 'string',
      transform: ['trim'],
      synonyms: ['name', 'product title', 'product name'],
    },
    {
      key: 'handle',
      label: 'Handle',
      required: true,
      type: 'string',
      transform: ['trim'],
      synonyms: ['slug', 'url handle', 'product handle'],
    },
    {
      key: 'status',
      label: 'Status',
      required: true,
      type: 'enum',
      enumValues: ['active', 'draft', 'archived'],
      synonyms: ['state', 'product status'],
    },
    {
      key: 'published',
      label: 'Published',
      required: true,
      type: 'boolean',
      transform: ['boolean'],
      synonyms: ['visible', 'is live', 'is published'],
    },
    {
      key: 'variant_sku',
      label: 'Variant SKU',
      required: true,
      type: 'string',
      transform: ['trim', 'upper'],
      synonyms: ['sku', 'product sku'],
    },
    {
      key: 'variant_price',
      label: 'Variant Price',
      required: true,
      type: 'number',
      transform: ['number'],
      synonyms: ['price', 'cost', 'amount'],
    },
    {
      key: 'body_html',
      label: 'Body (HTML)',
      type: 'string',
      synonyms: ['description', 'body', 'content'],
    },
    {
      key: 'vendor',
      label: 'Vendor',
      type: 'string',
      transform: ['trim'],
      synonyms: ['brand', 'manufacturer', 'supplier'],
    },
    {
      key: 'product_category',
      label: 'Product Category',
      type: 'string',
      transform: ['trim'],
      synonyms: ['category', 'type', 'product type'],
    },
    {
      key: 'tags',
      label: 'Tags',
      type: 'string',
      synonyms: ['keywords', 'labels'],
    },
    {
      key: 'variant_inventory_qty',
      label: 'Variant Inventory Qty',
      type: 'number',
      transform: ['number'],
      synonyms: ['inventory', 'qty', 'stock', 'quantity', 'available'],
    },
    {
      key: 'variant_inventory_policy',
      label: 'Variant Inventory Policy',
      type: 'enum',
      enumValues: ['deny', 'continue'],
      synonyms: ['backorders', 'inventory policy', 'out of stock policy'],
    },
    {
      key: 'image_src',
      label: 'Image Src',
      type: 'string',
      synonyms: ['image url', 'photo', 'image', 'picture'],
    },
  ],
};