import { Template } from '../types';

export const stripeCustomersTemplate: Template = {
  key: 'stripe-customers',
  title: 'Stripe Customers',
  templateVersion: '2025.1.0',
  ruleVersion: '1.0.0',
  sourceUrls: [
    'https://docs.stripe.com/stripe-data/import-external-data',
    'https://docs.stripe.com/stripe-data/import-external-data/data-template',
    'https://docs.stripe.com/get-started/data-migrations/export-file-formats'
  ],
  lastVerified: '2025-01-14',
  notes: [
    'Based on Stripe Data Management import specifications (2025)',
    'UTF-8 encoding required, comma-delimited values',
    'Email required and validated (RFC-compliant, permissive)',
    'Country: accepts ISO-2 codes or common names → normalizes to ISO-2',
    'Phone: accepts any format, suggests E.164 (non-fatal)',
    'Address fields optional, trimmed and collapsed whitespace',
    'All fields containing commas must be wrapped in double quotes',
    'Empty fields left entirely empty (no character between delimiters)',
  ],
  fields: [
    {
      key: 'email',
      label: 'Email',
      required: true,
      type: 'string',
      transform: ['trim'],
      synonyms: ['e-mail', 'email address', 'correo', 'courriel', 'e-mail-adresse', 'indirizzo email'],
    },
    {
      key: 'name',
      label: 'Name',
      type: 'string',
      transform: ['trim'],
      synonyms: ['full name', 'customer name', 'display name', 'nombre', 'nom complet', 'vollständiger name', 'nome completo'],
    },
    {
      key: 'description',
      label: 'Description',
      type: 'string',
      transform: ['trim'],
      synonyms: ['notes', 'memo', 'comment'],
    },
    {
      key: 'phone',
      label: 'Phone',
      type: 'string',
      transform: ['trim'],
      synonyms: ['telephone', 'phone number', 'mobile', 'teléfono', 'téléphone', 'telefon', 'telefono', 'móvil', 'portable'],
    },
    {
      key: 'address_line1',
      label: 'Address Line 1',
      type: 'string',
      transform: ['trim'],
      synonyms: ['addr1', 'address1', 'street address', 'address', 'dirección', 'adresse', 'indirizzo', 'calle', 'rue', 'straße'],
    },
    {
      key: 'address_line2',
      label: 'Address Line 2',
      type: 'string',
      transform: ['trim'],
      synonyms: ['addr2', 'address2', 'apt', 'suite', 'unit'],
    },
    {
      key: 'city',
      label: 'City',
      type: 'string',
      transform: ['trim'],
      synonyms: ['suburb', 'town', 'ciudad', 'ville', 'stadt', 'città'],
    },
    {
      key: 'state',
      label: 'State',
      type: 'string',
      transform: ['trim'],
      synonyms: ['province', 'region', 'state/province'],
    },
    {
      key: 'postal_code',
      label: 'Postal Code',
      type: 'string',
      transform: ['trim', 'upper'],
      synonyms: ['zip', 'postcode', 'zip code'],
    },
    {
      key: 'country',
      label: 'Country',
      type: 'string',
      transform: ['trim', 'upper'],
      synonyms: ['country code', 'nation', 'país', 'pays', 'land', 'paese', 'nazione'],
    },
  ],
};