name: "Bug report"
description: "Something failed or produced a bad CSV"
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: "Steps to reproduce"
      description: "What you did, expected vs actual"
  - type: input
    id: schema
    attributes: 
      label: "Schema"
      placeholder: "shopify-products | shopify-inventory | stripe-customers"
  - type: textarea
    id: sample
    attributes:
      label: "Sample rows"
      description: "Paste 3–5 rows (sanitize sensitive data)"