name: Bug Report
description: Report a problem with SchemaMap
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of SchemaMap is affected?
      options:
        - Web App (schemamap.app)
        - CLI (@schemamap/cli)
        - Mapping Engine
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: schema
    attributes:
      label: Schema
      description: Which schema were you working with?
      options:
        - Shopify Products
        - Shopify Inventory
        - Stripe Customers
        - Other/Not applicable
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Upload CSV with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: csv_sample
    attributes:
      label: CSV Sample (Optional)
      description: If possible, provide a sample of your CSV data (remove sensitive information)
      placeholder: |
        Header1,Header2,Header3
        value1,value2,value3
        ...

  - type: dropdown
    id: browser
    attributes:
      label: Browser (Web App issues)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - N/A (CLI issue)

  - type: input
    id: version
    attributes:
      label: Version
      description: CLI version (run `schemamap --version`) or "Web App" for browser
      placeholder: e.g., 1.0.0 or "Web App"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem