name: "Template request"
description: "Ask for a new target schema"
labels: ["template-request","help wanted"]
body:
  - type: input
    id: target
    attributes: 
      label: "Target platform"
      placeholder: "e.g., WooCommerce Products"
  - type: textarea
    id: spec
    attributes: 
      label: "Spec links"
      description: "Docs or example CSV"